name: Copy folder to other branch

on: 
  push:
    branches:
      - master
    paths-ignore:
      - '.github/workflows'
      - '**/file1.txt'
      - '**/file2.txt'

jobs:
  copy:
    name: Copy my folders
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: copy files to main-canada-2 branch
        env:
          SRC_FOLDER_PATH: './'
          TARGET_BRANCH: 'copy1'
        run: |
          ls -lsa
          #files="$(find $SRC_FOLDER_PATH -type f)" # get the file list
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git fetch                         # fetch branches
          git checkout $TARGET_BRANCH       # checkout to your branch
          for i in ./* ; do git checkout ${GITHUB_REF##*/} -- "$i"; done
          #git checkout ${GITHUB_REF##*/} -- $files # copy files from the source branch
          git add -A
          git diff-index --quiet HEAD ||  git commit -am "deploy files"  # commit to the repository (ignore if no modification)
          git push origin $TARGET_BRANCH # push to remote branch
