name: Copy folder to other branch

on: 
  workflow_dispatch:
  push:
    branches:
      - master


jobs:
  copy:
    name: Copy my folders
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          ref: master
        
      - name: copy files to main-canada-2 branch
        env:
          SRC_FOLDER_PATH: './'
          TARGET_BRANCH: 'copy'
        run: |
          git status
          ls -lsa
          files="$(find $SRC_FOLDER_PATH -type f)" # get the file list
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git fetch --all                       # fetch branches
          git checkout $TARGET_BRANCH       # checkout to your branch
          for i in "$files" ; do echo "$i" |& tee -a names.txt; done
          #echo $files > names.txt
          #sed -i '/.\/names.txt/d' names.txt 
          sed -i '/\.\/test\/file1\.txt/d' names.txt
          sed -i '/\.\/test\/file2\.txt/d' names.txt
          while IFS= read -r line; do echo $line; done < names.txt
          #git checkout master -- ./ # copy files from the source branch
          rm names.txt
          git add -A
          git status
          git diff-index --quiet HEAD ||  git commit -m "deploy files"  # commit to the repository (ignore if no modification)
          git push origin $TARGET_BRANCH # push to remote branch
